# Generated by Django 5.0.1 on 2024-02-03 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_code', models.CharField(max_length=64)),
                ('l_room', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='c_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_locations', to='courses.location'),
        ),
    ]
