# Generated by Django 5.0.1 on 2024-02-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_location_alter_course_c_loc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='courses.course')),
            ],
        ),
    ]
